export const createInitialState = () => ({
  screen: "play",
  level: 1,
  stars: 0,
  maxStars: 3,
  score: 0,
  mastery: {},
  totalRequired: 0,
  completedMastery: 0,
  spawnCount: 0,
  spawnBag: [],
  weakItemQueue: [],
  categoryHistory: [],
  levelIndex: 0,
  itemIndex: 0,
  activeItems: [],
  nextItemIndex: 0,
  itemSerial: 0,
  correct: 0,
  feedback: null,
  placed: null,
  completedLevel: false,
  muted: false,
  paused: false,
});
